# -*- coding: utf-8 -*-
"""fibonacci.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/casc12/ccaa9a1dd76df6fa1015b8400cf1a549/untitled0.ipynb
"""

def fibo(lastnum):
  a = 0
  b = 1

  while a < lastnum:
    print(a)
    r = a + b
    #p0 r = 0 + 1  = 1
    #p1 r = 1 +1 = 2
    #p2 r = 1 + 2 = 3
    a = b
    # p0 a = 1
    #p1 a =1
    #p2 = 2
    b = r
    #p0 b = 1
    #p1 b = 2
    #p2 = 3

    #print(a)
    #p0 = 1
    #p1 = 1
    #p2 = 2


fibo(100)

